<?php require_once("init.php"); ?>
<!DOCTYPE html>
<html>
  <head>
    <title>STEP Portal</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=0.7">
    <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/themes/smoothness/jquery-ui.css" />
    <?php if($ini["devmode"]) { ?>
    <link rel="stylesheet" href="css/style.css" />
    <script src="js/lib/require.js" data-main="js/init"></script>
    <?php } else { ?>
    <link rel="stylesheet" href="build/style.css" />
    <script src="build/require.js" data-main="build/step"></script>
    <?php } ?>
  </head>
  <body>
    <!-- application container -->
    <div id="step-container">
      <!-- the actual OpenLayers map -->
      <div id="map-view" title="Click on location icon for details"></div>
      <!--  header -->
      <!-- <div id="step-header">
        <div id="step-header-more-info" class="step-header-content-block">
          <p class="title no-margin">More information:</p>
          <ul>
            <li><a href="http://www.mywaterquality.ca.gov/monitoring_council/bioaccumulation_oversight_group/">Monitoring programs and reports</a></li>
            <li><a href="http://www.ceden.org/">Access Complete Datasets from CEDEN</a></li>
            <li><a href="http://www.mywaterquality.ca.gov/safe_to_eat/thresholds">Assessment thresholds</a></li>
          </ul>
          <a id="a-map-instructions" href="#">Map Instructions</a>
        </div>
        <div id="step-header-attributions" class="step-header-content-block">
          <p class="title no-margin" style="margin-bottom:5px;">This map shows data generated by:</p>
          <div class="step-header-logo-link">
            <a href="http://www.waterboards.ca.gov/water_issues/programs/swamp/">
              <img src="images/swamp.gif" class="attribution-logo" alt="SWAMP" /><br />
              SWAMP
            </a>
          </div>
          <div class="step-header-logo-link">
            <a href="http://www.sfei.org">
              <img src="images/SFEI.png" class="attribution-logo" alt="SFEI" /><br />
              SFEI
            </a>
          </div>
          <div class="step-header-logo-link">
            <a href="http://www.ceden.org">
              <img src="images/poweredbyceden.jpg" class="attribution-logo" alt="CEDEN" /><br />
              CEDEN
            </a>
          </div>
        </div>
      </div> -->
      <!-- layer/data controls -->
      <div id="controls-container" style="visibility:hidden;">
        <!-- <div id="controls-header">Safe-to-Eat Portal</div> -->
        <!-- filter/query controls -->
        <div id="control-tab-query" class="control-tab"><i></i>Filter Stations on Map</div>
        <div id="query-controls" class="controls-group">
          <!-- species -->
          <div id="control-label-species" class="control-label">Select a Species: </div>
          <select id="species-control" disabled>
            <option>Loading..</option>
          </select>
          <div class="control-spacer"></div>
          <!-- contaminants -->
          <div id="control-label-contaminant" class="control-label">Select a Contaminant: </div>
          <select id="contaminant-control" disabled>
            <option>Loading..</option>
          </select> 
          <div class="control-spacer"></div>
          <!-- thresholds -->
          <div id="control-label-thresholds" class="control-label">Select Contaminant Thresholds: </div>
          <select id="thresholds-control" disabled>
            <option>Loading..</option>
          </select>
          <div class="control-spacer"></div>
          <!-- years -->
          <div id="control-label-year-range" class="control-label">Select a Year Range:</div>
          <div id="control-year-range-container">
            Loading..
          </div>
          <div class="control-spacer"></div>
          <!-- other controls -->
          <div id="show-no-data-container">
            <input type="checkbox" id="show-no-data-control" disabled />
            Hide stations with no results
          </div>
          <div class="control-spacer"></div>
          <div id="reset-controls" class="button">
            Reset To Initial Settings
          </div>
        </diV>
        <!-- search by location controls -->
        <div id="control-tab-location" class="control-tab"><i></i>Find by Location</div>
        <div id="location-controls" class="controls-group">
          <div class="control-label">Zoom to County:</div>
          <select id="counties-select" data-placeholder="Zoom to County.." disabled>
            <option>Loading..</option>
          </select>
          <div class="control-spacer"></div>
          <div class="control-label">Zoom to Station:</div>
          <select id="stations-select" data-placeholder="Select a Location.." disabled>
            <option>Loading..</option>
          </select>
        </div>
        <!-- map/layer controls -->
        <div id="control-tab-map" class="control-tab"><i></i>Map/Layer Options</div>
        <div id="map-controls" class="controls-group">
          <div class="control-label-inline">Base Layer:</div>
          <div id="base-layer-control-container"></div>
          <div class="control-spacer"></div>
          <div title='California County Subdivisions' class="control-label-inline">Show CA Counties Layer:</div>
          <input type="checkbox" id="show-counties-control" disabled />
          <div class="control-spacer"></div>
          <div title='Water Board Region Subdivisions' class="control-label-inline">Show CA Water Board Regions:</div>
          <input type="checkbox" id="show-waterboards-control" disabled />
          <div class="control-spacer"></div>
          <div title='Marine Protected Areas in California' class="control-label-inline">Show Marine Protected Areas:</div>
          <input type="checkbox" id="show-mpa-control" disabled />
        </div>
        <!-- about -->
        <div id="control-tab-about" class="control-tab"><i></i>About</div>
        <div id="about-controls" class="controls-group">
          <p>
            This interactive map allows you to explore fish contaminant data for your fishing locations. Data 
            are available from extensive monitoring by SWAMP of lakes and reservoirs in 2007 and 2008, of the 
            coast in 2009 and 2010, of rivers and streams in 2011, and from other studies.
          </p>
          <div id="btn-map-instructions" class="btn">Map Instructions</div>
          <p class="bold no-margin" style="margin-bottom:5px;">This map shows data generated by:</p>
          <div id="step-header-logo-container">
            <div class="step-header-logo-link">
              <a href="http://www.waterboards.ca.gov/water_issues/programs/swamp/">
                <img src="images/swamp.gif" class="attribution-logo" alt="SWAMP" /><br />
                SWAMP
              </a>
            </div>
            <div class="step-header-logo-link">
              <a href="http://www.sfei.org">
                <img src="images/SFEI.png" class="attribution-logo" alt="SFEI" /><br />
                SFEI
              </a>
            </div>
            <div class="step-header-logo-link">
              <a href="http://www.ceden.org">
                <img src="images/poweredbyceden.jpg" class="attribution-logo" alt="CEDEN" /><br />
                CEDEN
              </a>
            </div>
          </div>
        </div>
        <!-- more info -->
        <div id="control-tab-more-info" class="control-tab"><i></i>More Information</div>
        <div id="more-info-controls" class="controls-group">
          <p class="bold no-margin">More information:</p>
          <ul>
            <li><a href="http://www.mywaterquality.ca.gov/monitoring_council/bioaccumulation_oversight_group/">Monitoring programs and reports</a></li>
            <li><a href="http://www.ceden.org/">Access Complete Datasets from CEDEN</a></li>
            <li><a href="http://www.mywaterquality.ca.gov/safe_to_eat/thresholds">Assessment thresholds</a></li>
          </ul>
        </div>
        <div id="additional-buttons">
          <div id="zoom-stations-tab" class="button-tab">Fit View to Stations</div>
          <div id="download-tab" class="button-tab">Download Data</div>
        </div>
      </div>
      <!-- notification popup thingamajig -->
      <div id="notification-container">
        <div id="notification-tab">Notifications go here</div>
      </div>
    </div>
  </body>
</html>
